name: MT6750 k63v2 APatch
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # 修复yylloc重复定义DTC报错
      - name: 修复DTC多重变量冲突
        run: |
          sed -i '/YYLTYPE yylloc/d' scripts/dtc/dtc-lexer.l
          sed -i '/YYLTYPE yylloc/d' scripts/dtc/dtc-parser.y
          echo 'EXTRA_CFLAGS += -fcommon' >> scripts/dtc/Makefile

      # 修复OpenSSL3废弃函数报错
      - name: 屏蔽OpenSSL警告终止编译
        run: sed -i 's/-Werror//g' scripts/Makefile

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential flex bison libncurses-dev libssl-dev bc device-tree-compiler python3

      - name: GCC4.9交叉编译器
        run: git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc

      - name: DrvGen权限+Python3
        run: |
          sudo chmod -R 777 tools/dct
          sed -i 's/python/python3/g' tools/dct/DrvGen.py

      - name: 加载机型配置
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-android-
          make mrproper
          make k63v2_64_bsp_defconfig

      - name: APatch Root全符号
        run: sed -i 's/# CONFIG_KALLSYMS_ALL/CONFIG_KALLSYMS_ALL=y/' .config

      - name: 编译内核vmlinuz
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-android-
          make -j$(nproc) Image.gz-dtb
          cp arch/arm64/boot/Image.gz-dtb vmlinuz

      - name: 下载成品内核
        uses: actions/upload-artifact@v4
        with:
          name: MT6750-boot
          path: |
            arch/arm64/boot/Image.gz-dtb
            vmlinuz

